<script lang="ts">
	import { onMount } from 'svelte';
	import { supabase } from '$lib/supabase/client';
	type State = 'success' | 'warning' | 'error';
	type Service = { name: string; state: State; latency: number | null; message: string };
	let overallState = $state<State>('warning'); let expanded = $state(false); let copied = $state(false); let checkedAt = $state<Date | null>(null);
	let services = $state<Service[]>([{ name: 'Base de datos', state: 'warning', latency: null, message: 'Comprobando…' }, { name: 'Autenticación', state: 'warning', latency: null, message: 'Comprobando…' }, { name: 'Almacenamiento', state: 'warning', latency: null, message: 'Comprobando…' }]);
	let sessionId = $state(''); let transferred = $state(0); const build = 'Tiendly web';
	const config = { success: { icon: 'ri-check-line', label: 'Operativo', color: 'text-emerald-300 bg-emerald-500/15 border-emerald-400/30' }, warning: { icon: 'ri-alert-line', label: 'Advertencia', color: 'text-amber-300 bg-amber-500/15 border-amber-400/30' }, error: { icon: 'ri-close-circle-line', label: 'Error', color: 'text-red-300 bg-red-500/15 border-red-400/30' } } as const;
	function browser() { return navigator.userAgent.includes('Chrome') ? 'Chrome' : navigator.userAgent.includes('Firefox') ? 'Firefox' : navigator.userAgent.includes('Safari') ? 'Safari' : 'Navegador'; }
	function os() { return navigator.userAgent.includes('Windows') ? 'Windows' : navigator.userAgent.includes('Mac') ? 'macOS' : navigator.userAgent.includes('Android') ? 'Android' : navigator.userAgent.includes('Linux') ? 'Linux' : 'Sistema operativo'; }
	function cacheMb() { return 'caches' in window ? 'calculando' : '0.0'; }
	function report() { const server = services.map((s: Service) => `${s.name}: ${config[s.state].label} · ${s.latency ?? 'n/d'} ms${s.state === 'error' ? ` · ${s.message}` : ''}`).join('\n'); return `Tiendly — diagnóstico ${sessionId}\n\nServidor\n${server}\n\nCliente\nNavegador: ${browser()}\nSistema operativo: ${os()}\nBuild: ${build}\nCaché usada: ${cacheMb()} MB\nDatos transferidos: ${transferred.toFixed(1)} KB\nChequeo: ${checkedAt?.toLocaleString('es-CU') ?? 'n/d'}`; }
	async function check() { const started = performance.now(); const result = await supabase.from('stores').select('id', { head: true, count: 'exact' }).limit(1); const latency = Math.round(performance.now() - started); const db: Service = { name: 'Base de datos', state: result.error ? 'error' : latency > 1500 ? 'warning' : 'success', latency, message: result.error?.message ?? 'Respuesta correcta' }; services = [db, { name: 'Autenticación', state: result.error ? 'error' : 'success', latency, message: result.error?.message ?? 'Disponible' }, { name: 'Almacenamiento', state: result.error ? 'warning' : 'success', latency, message: result.error?.message ?? 'Disponible' }]; overallState = services.some((s) => s.state === 'error') ? 'error' : services.some((s) => s.state === 'warning') ? 'warning' : 'success'; checkedAt = new Date(); }
	async function copy() { await navigator.clipboard.writeText(report()); copied = true; setTimeout(() => copied = false, 1600); }
	onMount(() => { sessionId = crypto.randomUUID().slice(0, 8).toUpperCase(); check(); const timer = setInterval(check, 30000); return () => clearInterval(timer); });
</script>
<div class="relative z-10 flex items-center justify-center">
	<button type="button" class={`flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-semibold shadow-sm transition-all ${config[overallState].color}`} onclick={() => expanded = !expanded} aria-expanded={expanded}><i class={config[overallState].icon} aria-hidden="true"></i><span class="hidden sm:inline">{config[overallState].label}</span>{#if services[0].latency !== null}<span class="font-mono text-[10px] opacity-75">{services[0].latency}ms</span>{/if}</button>
	{#if expanded}<div class="absolute left-1/2 top-[calc(100%+0.65rem)] z-20 w-80 max-w-[calc(100vw-32px)] -translate-x-1/2 rounded-2xl border border-hairline bg-card p-4 text-left shadow-2xl"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold text-ink">Diagnóstico de servicio</h2><button type="button" class="text-muted" onclick={() => expanded = false} aria-label="Cerrar"><i class="ri-close-line"></i></button></div><h3 class="mb-1 text-xs font-semibold uppercase tracking-wider text-muted">Servidor</h3>{#each services as service (service.name)}<div class="flex items-center justify-between border-b border-hairline py-2 text-xs"><span class="text-body">{service.name}</span><span class={config[service.state].color + ' rounded-full border px-2 py-0.5'}>{config[service.state].label} · {service.latency ?? 'n/d'} ms</span></div>{/each}<h3 class="mb-1 mt-4 text-xs font-semibold uppercase tracking-wider text-muted">Cliente</h3><div class="space-y-1 text-xs text-body"><p>Navegador: {browser()}</p><p>Sistema: {os()}</p><p>Build: {build}</p><p>Caché usada: {cacheMb()} MB</p><p>Transferidos: {transferred.toFixed(1)} KB</p><p>Sesión: {sessionId} · {checkedAt?.toLocaleTimeString('es-CU') ?? 'n/d'}</p></div><button type="button" class="btn btn-secondary btn-sm mt-4 flex w-full items-center justify-center gap-2" onclick={copy}><i class={copied ? 'ri-check-line' : 'ri-file-copy-line'}></i>{copied ? 'Copiado' : 'Copiar diagnóstico'}</button></div>{/if}
</div>
