name: release-main

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-bot
  cancel-in-progress: false

jobs:
  bot:
    uses: rblez/workflows/.github/workflows/release-bot.yml@main
