name: release-main

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-bot
  cancel-in-progress: false

jobs:
  bot:
    uses: rblez/.github/.github/workflows/release-bot.yml@994f8d213619e6bb83a4b90c9ca0d2473a3fa1cf
